### ISSUE TITLE
Cannot use classes like `ItemNotFoundError` because target is set to `es5`

### ISSUE THREAD

**Issue by powerpaul17** [blinkdb-js/blinkdb#21]
I cannot check an error with `instanceof ItemNotFoundError` because in the compiled file classes get converted into functions. I think it is because you target `es5` in the `tsconfig.json`.

I don't know if it is desired/necessary to target `es5` for some reason, otherwise would it be possible to change it to `es6`?

Thank you for this great project! :slightly_smiling_face:

**Comment by froehlichA** [comment]
Yep, I'm taking a look at it.

**Comment by froehlichA** [comment]
Nice! That was exactly the problem. Fixed in [the latest release](https://www.npmjs.com/package/blinkdb/v/0.13.2).
