### ISSUE TITLE
Is there a way to do sync queries?

### ISSUE THREAD

**Issue by retorquere** [blinkdb-js/blinkdb#26]
The async methods all seems to consist of wrapping the result of what are essentially sync functions in a Promise.resolve. Is there a way to skip this? There are parts of my application where I cannot run async code.

**Comment by froehlichA** [comment]
For now, although the API is internal, you can keep using `const { internalInsertMany } = require('blinkdb/dist/core/insertMany')` to import the synchronous methods.

In the future (after v1.0), I will extract the entire synchronous database into a `@blinkdb/core` module, which will make it easier if you just want to use the underlying synchronous DB implementation without any hooks.

**Comment by retorquere** [comment]
`internalInsertMany` still returns a promise though. I hadn't looked closely enough.

WRT hooks, even if I were to de-promisify the internal methods, they still wouldn't trigger hooks then, right? That would be a problem for me, alas. There are sections of my code where I have no choice but to use sync methods.

Is there a rough timeline how far off this future is?

**Comment by froehlichA** [comment]
> Is there a rough timeline how far off this future is?

I'll get to it as soon as I finish the vue package, which is the current item on my todo list. I'd expect the extracting to `@blinkdb/core` to be done probably by end of this year.

**Comment by retorquere** [comment]
Any news on this?

**Comment by retorquere** [comment]
@maradotwebp I have a series of putout codemods that strips blinkdb to sync but I'd much prefer it if it would be part of a formal release.
