### ISSUE TITLE
value.some is not a function

### ISSUE THREAD

**Issue by ericvida** [blinkdb-js/blinkdb#34]
![CleanShot 2023-11-30 at 21 36 03@2x](https://github.com/blinkdb-js/blinkdb/assets/13579055/ae302613-1e8f-4927-801b-161d0ddf4dd8)

I'm getting an odd issue, where if I pass an object for the contain query `{contain: 'bob'}` it throws an error. If I make it an array as the error seems to suggest `[ {contains: 'bob'}]` for example, I don't get an error, but I don't get results.

I'm following the documentation formatting:
![CleanShot 2023-11-30 at 21 35 44@2x](https://github.com/blinkdb-js/blinkdb/assets/13579055/da67e165-958d-49de-a683-a65c27a185ab)

I code in [imba](https://imba.io) which compiles to vanilla js. Not sure if this has anything to do with it not being typescript.
![CleanShot 2023-11-30 at 21 35 14@2x](https://github.com/blinkdb-js/blinkdb/assets/13579055/31a48421-a1b6-4d37-9f85-9763a4d2971e)

**Comment by froehlichA** [comment]
The [`contains`](https://blinkdb.io/docs/filters#contains) filter checks whether an array property contains a value (in my example, whether there are any entities in the db which have the value `Big Nick` in their string array property of `nicknames`), not whether a string property includes some substring, which I think is what you're trying to achieve here.

**Comment by ericvida** [comment]
Ahh. I see. I misread the docs. 
Is there a way to search for a substring in a string?

**Comment by froehlichA** [comment]
Nope, at least no efficient way. You'd have to retrieve all documents.
