### ISSUE TITLE
How to count the entries effectively?

### ISSUE THREAD

**Issue by shtse8** [blinkdb-js/blinkdb#7]
I can't find any example how to get the total rows in collections effectively.

Currently, I am using
```js
const total = await many(users).then(x => x.length)
```
But obviously it is not a good approach.

**Comment by froehlichA** [comment]
Yep, that's currently the only way.

I'll implement a count function as soon as possible.

**Comment by froehlichA** [comment]
`count()` is now implemented in a much more performant way in [the latest release](https://github.com/blinkdb-js/blinkdb/releases/tag/v0.9.0).
